### ISSUE TITLE
Integrate Travis CI + Coveralls

### ISSUE THREAD

**Issue by ddnomad** [zeroguard/zeroguard-sdk-javascript#2]
Example integration implemented in our Python SDK: https://github.com/zeroguard/zeroguard-sdk-python/blob/master/.travis.yml. This would obviously require some JS-specific amendments.

**Comment by Dubbinary** [comment]
Integrated in https://github.com/zeroguard/zeroguard-sdk-javascript/commit/8c3cd7aec1b69a1a046c539b79c0217066860bcf
